In [3]:
import pandas as pd
df = pd.read_csv("../data/ONS_regional_fulltime_salary_data.csv") ## ../ <-- goes back one folder, then into the data folder to obtain the regional full-time data
print(df.head(10)) #shows the first 5 rows. e.g., df.head(10) shows the first 10 rows

                Description       Code Median
0             Darlington UA  E06000005  36166
1             Hartlepool UA  E06000001  31871
2          Middlesbrough UA  E06000002  35177
3   Redcar and Cleveland UA  E06000003  35111
4       Stockton-on-Tees UA  E06000004  37558
5          County Durham UA  E06000047  33436
6         Northumberland UA  E06000057  37721
7  Tyne and Wear Met County  E11000007  34558
8                 Gateshead  E08000037  34199
9       Newcastle upon Tyne  E08000021  35446

In [5]:
#In order to join the data with the Median House Prices by County, cleaning of County Names is required.

df['Description'] = (
    df['Description']
    .str.upper() #makes local authority name upper case
    .str.strip() #removes leading or trailing spaces
    .str.replace(' UA', '', regex=False) #removes "_UA" from end of local authority name
    .str.replace(' MET COUNTY', '', regex=False) #removes "Met County" from end of local authority name
)

In [27]:
print(df.head())
df['Median'] = pd.to_numeric(
    df['Median'], #converts median to number
    errors='coerce') #found error in median salary for two local authorities - in spreadhseet, these were labelled x. Changed to NaN values
df[df['Median'].isna()]

            Description       Code   Median
0            DARLINGTON  E06000005  36166.0
1            HARTLEPOOL  E06000001  31871.0
2         MIDDLESBROUGH  E06000002  35177.0
3  REDCAR AND CLEVELAND  E06000003  35111.0
4      STOCKTON-ON-TEES  E06000004  37558.0

         Description       Code  Median
193   CITY OF LONDON  E09000001     NaN
306  ISLES OF SCILLY  E06000053     NaN

In [31]:
df = df.dropna(subset=['Median']) #dropping NaN rows for easier joining
df[df['Median'].isna()]

Empty DataFrame
Columns: [Description, Code, Median]
Index: []

In [33]:
df = df.rename(columns={
    'Description': 'local_authority',
    'Code': 'ons_code',
    'Median': 'median_salary'
})

In [35]:
df

          local_authority   ons_code  median_salary
0              DARLINGTON  E06000005        36166.0
1              HARTLEPOOL  E06000001        31871.0
2           MIDDLESBROUGH  E06000002        35177.0
3    REDCAR AND CLEVELAND  E06000003        35111.0
4        STOCKTON-ON-TEES  E06000004        37558.0
..                    ...        ...            ...
374        SOUTH AYRSHIRE  S12000028        43076.0
375     SOUTH LANARKSHIRE  S12000029        41126.0
376              STIRLING  S12000030        43559.0
377   WEST DUNBARTONSHIRE  S12000039        40011.0
378          WEST LOTHIAN  S12000040        40134.0

[377 rows x 3 columns]

In [37]:
df.to_csv(
    '../data/ashe_clean.csv',
    index=False
)